version: '3.3'
services:
  #PHP
  php:
    build:
      context: ./dockerfiles/php
    container_name: project-name-be
    restart: always
    env_file:
      - ./.env
    volumes:
      - "../:/var/www/project:cached"
    working_dir: /var/www/project

  #NGNIX
  ngnix:
    image: nginx:1.13-alpine
    container_name: project-name-web
    restart: always
    ports:
      - "80"
    env_file:
      - ./.env
    volumes:
      - "./dockerfiles/nginx/project.conf:/etc/nginx/conf.d/default.conf:ro"
      - "../:/var/www/project:cached"
    working_dir: /var/www/project
    depends_on:
      - php

  # Database
  postgres-10:
    image: postgres:10-alpine
    user: "root"
    restart: always
    container_name: postgres
    environment:
      - "POSTGRES_DB=${DATABASE_NAME}"
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
    ports:
      - "${POSTGRES_PUBLISHED_PORT}:5432"

  pgadmin-4-2.0:
    image: fenglc/pgadmin4:2.0
    restart: always
    environment:
      - "DEFAULT_USER=${DATABASE_USER}"
      - "DEFAULT_PASSWORD=${DATABASE_PASSWORD}"
    ports:
      - "5050:5050"

  redis-3.2.11:
    image: redis:3.2.11
    restart: always
    ports:
      - "${REDIS_PUBLISHED_PORT}:6379"